# -*- coding: utf-8 -*-
"""Визуализация.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12LjrQevpjX-Ks-KNfzOyZxktvFInU-1z
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

import warnings; warnings.simplefilter('ignore')

df = pd.read_csv('tips.csv')

sns.set()
sns.distplot(df['total_bill'])

sns.jointplot(x = 'total_bill', y = 'tip', data = df)

sns.jointplot(x = 'total_bill', y = 'tip', data = df, kind = 'reg')

sns.pairplot(df)

sns.jointplot(x = 'total_bill', y = 'tip', data = df, kind = 'hex')

#гистограммы распределения категориального признака
sns.countplot(x = 'day', data = df)

sns.barplot(x = 'sex', y = 'total_bill', data = df)

sns.boxplot(x = 'day', y = 'tip', data = df)

sns.boxplot(x = 'day', y = 'tip', data = df, hue = 'smoker')

sns.pairplot(df, hue = 'smoker')

correlation = df.corr()

sns.heatmap(correlation,annot = True,cmap='coolwarm')

!pip install plotly
!pip install cufflinks

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import cufflinks as cf
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
# %matplotlib inline

init_notebook_mode(connected = True)
cf.go_offline()

df = pd.read_csv('tips.csv')